### PR TITLE
Add mabl logo to the README

### PR DESCRIPTION
**Pull request by srvance**

### CODE REVIEW

**Comment by srvance** [comment]
Looks like it came in pretty large. Let me know what size you'd like to target.

**Comment by tshaddix** [comment]
Such a cool logo! Do you happen to have one that has a height between 50px and 100px?

**Comment by srvance** [comment]
Thank you! I adjusted the markdown to scale the logo. Does that work for you?

**Comment by tshaddix** [comment]
Perfect! Merging now

**Pull request merged**
