### PR TITLE
Redux v4 and moved to peer dependency

### PR DESCRIPTION
**Pull request by craigsketchley**
I was having some issues with the typings in this library as I was using Redux v4.

I've updated Redux to version 4 and moved it to a peer dependency (assuming anyone who uses this library will already have their own Redux dependency).

Not sure why there's a whole bunch of `"optional": true` lines removed from the `package-lock.json`. Hope that's alright?

Let me know your thoughts - happy to make some changes if it's not up to scratch.

### CODE REVIEW

**Comment by craigsketchley** [comment]
Somewhat related to this... what's the reason you have the return type of dispatch as an action?

**Comment by craigsketchley** [comment]
Any thoughts on this? Happy to discuss further.

**Comment by tshaddix** [comment]
@craigsketchley Thanks for contributing! Sorry for the late response - I don't always have a chance to check these PRs out on my weekdays given my work schedule.

Is there a reason you're also including redux in the dev dependencies?

**Comment by craigsketchley** [comment]
Cheers @tshaddix, no worries at all. Yeah, so I was making the assumption that anyone who uses this library would/should have Redux already as a dependency. So we probably shouldn't package up a specific version of Redux with this library - that may/may not get used - so I moved it to `peerDependencies`. Since `peerDependencies` are only a requirement and are not actually installed, I added it as under `devDependencies` as we'll need it during development.

**Comment by craigsketchley** [comment]
I should probably widen the possible Redux version range to more than just `>= 4` since we know `webext-redux` works with older version of Redux too.

**Comment by VasilyShelkov** [comment]
This would close https://github.com/tshaddix/webext-redux/issues/221

**Comment by craigsketchley** [comment]
Any thoughts on this @tshaddix ? Happy to close or update if it's not helpful.

**Comment by tshaddix** [comment]
LGTM! Thanks @craigsketchley !

**Pull request merged**
