### PR TITLE
Add sender to alias result

### PR DESCRIPTION
**Pull request by pelegb**
I've been using your package for the past two weeks and have encountered the necessity to pass the sender object to the result of the alias function. I've updated a bit the alias middleware or am I missing something and there is a different way to do things?

Thanks for the pacakge

### CODE REVIEW

**Comment by tshaddix** [comment]
Hey @pelegb  - sorry for the super late response. Starting to dive in now.

Is there a reason that you wouldn't just pass the sender in your alias function?

e.g. This would be your alias function:

```js
function myAlias(originalAction) {
  return {
    type: "NEW_ACTION",
    payload: {
      // whatever props
    tabId: originalAction._sender.tab.id
    }
  };
}
```

The reason I'm suggesting this approach is ideally your alias layer is what translates "react-chrome-redux specific" logic into your "business" logic.

**Comment by pelegb** [comment]
I didn't want to add this piece of code to all my alias functions and all my reducers. This is important contextual information for me. 
My use case: A button in the content script call an API on the server. So I have a "callServer" alias.
This dispatches two actions:

1. An action to change the state to InProgress for this specific tab which requires the tab ID
2. A thunk which calls the server

The response action for the thunk requires the tab ID in order to update the state to finished.

Makes sense?
Do you have a different suggested solution?

Thanks for the great work.

**Comment by kaglowka** [comment]
I needed that too (needed tab id for every action to add it to appropriate tab state). I also wanted some kind of generic solution, since most of my actions were tab-specific. In the end I solved it by calling extra "transformation" on all background page thunks. It's a bit rough so I wouldn't call it the best approach but it is a workable alternative, so I'm posting it. Here's an example of `createResource`thunk:

```js
export function createResourceAlias(...args) {
  return { type: 'createResourceAlias', args };
}

export function aliasActionToTabMarkedThunk(originalThunk) {
  return (aliasAction) => {
    return (dispatch, getState) => {
      const tabId = retrieveActionTab(aliasAction);
      // attach the tab info to all actions dispatched within the thunk
      const newDispatch = action => dispatch(markInThunkActionWithTabId(action, tabId));
      return originalThunk(...aliasAction.args)(newDispatch, getState);
    };
  };
}

export function markInThunkActionWithTabId(action, tabId) {
  return {
    ...action,
    _meta: { tabId },
  };
}

```
Which is used like:
```js


const aliases = {
  createResourceAlias: aliasActionToTabMarkedThunk(createResource),
```

**Comment by tshaddix** [comment]
@kaglowka That makes since! 

@pelegb Got it! At the end of the day, there are a lot of options forward here. One option is to make a wrapper like @kaglowka . Another is to add your own `alias` middleware.

That said, if enough people need this `sender` object on their aliased actions (which I could see why), then I suggest we do the following:

1. Add an options parameter as the second argument of the `alias` middleware.
2. Add an option (default is `false`) called `includeSender`
3. If `includeSender` is true, then we do something similar to what you are referencing above.

Again - I'm not sure how widespread this issue is. Personally, I think the solution you came up with makes a lot of since (just spin your own middleware and include that instead). Regardless, if this was to make it into this library, I'd like to put it as an opt-in feature.

**Comment by tshaddix** [comment]
Also, correct me if I'm wrong, but this is a very `redux-thunk` specific solution, correct? Although `redux-thunk` is a great library, we probably shouldn't assume everyone who is using this library is using it. 

This is why I think the way you did it (or @kaglowka's way) is the best way. Just role your own middleware like you did and include that instead of the `alias` middleware :)

**Comment by pelegb** [comment]
It is a redux-thunk solution. Don't know enough of other redux async solutions to make it generic. If someone can assist it would be great.
I expect this to be quite a common use case for the users of webext-redux that I would expect this to be part of the library. As you suggested as an opt-in solution.

**Comment by tshaddix** [comment]
Thanks @pelegb . Given that this is a `redux-thunk` specific solution and is really just a reimplementation of the `alias` middleware, I would suggest that we pull this into its own middleware package such as `webext-redux-thunk`. This can export an `alias` function that can be used instead of the default in `webext-redux`.

**Pull request closed without merging**
